### ISSUE TITLE
Add randomness to filename

### ISSUE THREAD

**Issue by JackDunnNZ** [JuliaOpt/AmplNLWriter.jl#10]
If multiple solves are going at once, they all try to use the same files for model and solution

**Comment by mlubin** [comment]
CC @tkelman

**Comment by tkelman** [comment]
Yeah this is essentially the same issue as https://github.com/JuliaOpt/CoinOptServices.jl/issues/1, I didn't expect someone to be doing multiple simultaneous solves quite so quickly. If this package provides an API to provide a non-default write location for the files then maybe that's good enough if documented? I have been meaning to eventually switch to a randomized filename with default deletion when finished, unless a debug flag is set.

**Comment by JackDunnNZ** [comment]
Yeah, I was just firing off a few different things all at once to check #6 was fixed, and suddenly they were all messing up! I think either of those are good enough solutions
