### ISSUE TITLE
How to call Knitro

### ISSUE THREAD

**Issue by ulneva** [JuliaOpt/AmplNLWriter.jl#19]
I cannot figure out, using the examples, how I can call knitro (I have a full lisence, including for knitroampl) using AmplNLWriter. What line should I call? Many thanks!

**Comment by mlubin** [comment]
Resolved at https://groups.google.com/forum/#!topic/julia-opt/1G0MIkcHGlE

**Comment by ulneva** [comment]
Thanks, Miles!
