### ISSUE TITLE
Using Couenne options from AmplNLWriter

### ISSUE THREAD

**Issue by madeleineudell** [JuliaOpt/AmplNLWriter.jl#25]
I'm not sure if this is a problem with this interface or with my understanding of Couenne's options, but it doesn't seem like the options I specify affect the solver's behavior.

Here's a simple example:
```
using JuMP, AmplNLWriter

solver=AmplNLSolver("couenne", Dict("bonmin.allowable_gap"=>1, 
                         "outlev"=>0,
                         "output_file"=>"results.out"))
m = Model(solver=solver)

srand(4)
nvar = 10
@defVar(m, -10 <= x[i=1:nvar] <= 10)
@setNLObjective(m, Min, sum{1/(1+exp(-x[i])), i=1:nvar})
@addConstraint(m, sum{x[i], i=1:nvar} <= .4*nvar)
@assert(solve(m) == :Optimal)
```
The output is exactly the same regardless of how I specify the allowable gap and outlev, and the file results.out never shows up. However, it does seem like Couenne knows something about these options, since the output starts with
```
Couenne 0.5 -- an Open-Source solver for Mixed Integer Nonlinear Optimization
Mailing list: couenne@list.coin-or.org
Instructions: http://www.coin-or.org/Couenne
couenne: output_file=results.out
bonmin.allowable_gap=100
outlev=0
```

**Comment by JackDunnNZ** [comment]
My experience with Couenne is that it's not clear at all which options actually are respected. As you say, some seem to have no effect, like `bonmin.allowable_gap`. The only way I have successfully set some of the options is by using a `couenne.opt` file, which has to be placed in the working directory. Each line in this file should contain a key value pair, separated by a space, and seems to give access to more options than are supported by the command line. e.g. to set the allowable fractional gap:

    allowable_fraction_gap 0.05

We chose not to add solver specific behavior into AmplNLWriter, but if you write a file like this to the working directory before the solve, it will get picked up.

As an example, the `jump_pruning.jl` in the examples folder takes about 10s to converge using Couenne with no options set, but the following will successfully set the relative tolerance and exit early:

```
shell> echo 'allowable_fraction_gap 0.01' > couenne.opt

julia> solver = CouenneNLSolver()
AmplNLWriter.AmplNLSolver("/Users/jack/.julia/v0.4/Homebrew/deps/usr/lib/../bin/couenne",Dict{ASCIIString,Any}())

julia> include(joinpath(Pkg.dir("AmplNLWriter"), "examples", "jump_pruning.jl"))
  > example: jump_pruning
Couenne 0.5.6 -- an Open-Source solver for Mixed Integer Nonlinear Optimization
Mailing list: couenne@list.coin-or.org
Instructions: http://www.coin-or.org/Couenne
couenne:
ANALYSIS TEST: NLP0012I
              Num      Status      Obj             It       time                 Location
NLP0014I             1         OPT -400.00001       29 0.019526
Couenne: new cutoff value -4.0000000800e+02 (0.027305 seconds)
Loaded instance "/Users/jack/.julia/v0.4/AmplNLWriter/.solverdata/model.nl"
Constraints:            8
Variables:              2 (0 integer)
Auxiliaries:            9 (0 integer)

Coin0506I Presolve 24 (-2) rows, 6 (-5) columns and 59 (-9) elements
Clp0006I 0  Obj -399.99001 Primal inf 40.312967 (4) Dual inf 58.942108 (1)
Clp0006I 8  Obj -197487.48
Clp0000I Optimal - objective value -197487.48
Clp0032I Optimal objective -197487.4793 - 8 iterations time 0.002, Presolve 0.00
Clp0000I Optimal - objective value -197487.48
Cbc0012I Integer solution of -400.00001 found by Couenne Rounding NLP after 0 iterations and 0 nodes (0.00 seconds)
NLP Heuristic: NLP0014I             2         OPT -400.00001       20 0.014536
no solution.
Clp0000I Optimal - objective value -197487.48
Optimality Based BT: 8 improved bounds
Probing: 6 improved bounds
NLP Heuristic: no solution.
Cbc0031I 5 added rows had average density of 2.6
Cbc0013I At root node, 5 cuts changed objective from -197487.48 to -605.79249 in 16 passes
Cbc0014I Cut generator 0 (Couenne convexifier cuts) - 22 row cuts average 2.9 elements, 17 column cuts (17 active)
Cbc0010I After 0 nodes, 1 on tree, -400.00001 best solution, best possible -605.79249 (0.05 seconds)
Optimality Based BT: 5 improved bounds
Optimality Based BT: 3 improved bounds
Optimality Based BT: 8 improved bounds
Optimality Based BT: 8 improved bounds
Optimality Based BT: 7 improved bounds
Couenne: new cutoff value -4.0000435404e+02 (0.132964 seconds)
Optimality Based BT: 6 improved bounds
Optimality Based BT: 3 improved bounds
Optimality Based BT: 8 improved bounds
Optimality Based BT: 6 improved bounds
Optimality Based BT: 7 improved bounds
Couenne: new cutoff value -4.0000595361e+02 (0.216213 seconds)
Optimality Based BT: 7 improved bounds
Cbc0010I After 100 nodes, 42 on tree, -400.00001 best solution, best possible -403.86423 (0.22 seconds)
Cbc0011I Exiting as integer gap of 3.8642216 less than 0 or 1%
Cbc0001I Search completed - best objective -400.00000799999, took 439 iterations and 101 nodes (0.22 seconds)
Cbc0035I Maximum depth 15, 0 variables fixed on reduced cost

 	"Finished"

Linearization cuts added at root node:         26
Linearization cuts added in total:             26  (separation time: 0.000174s)
Total solve time:                        0.223931s (0.223931s in branch-and-bound)
Lower bound:                             -403.864
Upper bound:                             -400.006  (gap: 0.95%)
Branch-and-bound nodes:                       101
Performance of                           FBBT:	   0.002143s,      187 runs. fix:          0 shrnk:   0.139821 ubd:  0.0869166 2ubd:          0 infeas:          0
```

It's a bit of a pain, but hopefully it should work

**Comment by mlubin** [comment]
My experience with bonmin options is that they can be horribly broken. On a couple of occasions I've needed to hack the source to set specific options.

**Comment by madeleineudell** [comment]
Writing an options file in the directory from which I invoke the solver seems to work for some options, but not all. The options file `couenne.opt` reads
```
allowable_fraction_gap 5.0
output_file fn.out
```
For small problems, this writes the output file fn.out, but solves the problem exactly. For large problems... well, it's been running for a day so far, so my guess is it's still trying to solve the problem exactly. 

Miles, any advice on how to hack the source? (Or is there a different option name I should be using to tell the solver that a gap of 5 between the lower and upper bound would be perfectly ok with me?)

**Comment by JackDunnNZ** [comment]
I think you could try `allowable_gap 5.0` to set the absolute tolerance, `allowable_fraction_gap` sets the relative tolerance (sorry for the confusion!). It seems to work locally for me, it exits with:

    Cbc0011I Exiting as integer gap of 3.8642216 less than 5 or 0%

I've found the best way to find the relevant options is through the default `.opt` files (and a lot of trial and error....), e.g.
https://github.com/coin-or/Couenne/blob/master/Couenne/src/couenne.opt
https://github.com/coin-or/Bonmin/blob/master/Bonmin/test/bonmin.opt

For whatever reason, the bonmin options seem to work with and without the `bonmin.` prefix, but don't get set properly through the command line args i.e. `bonmin.allowable_gap` works from the `couenne.opt` file, but as you saw not if you pass it on the command line.

**Comment by JackDunnNZ** [comment]
Can you try the running the following to check if it works with the option setting (this is working on travis and appveyor as well as my machine):

```
using AmplNLWriter
solver = CouenneNLSolver()
open("couenne.opt", "w") do f
    write(f, "allowable_fraction_gap 0.0001")
end
include(joinpath(Pkg.dir("AmplNLWriter"), "examples", "jump_pruning.jl"))
```

Without the option file, it takes about 10 secs to converge, but with the tolerance it's about a second, and there's a message about exiting like `Exiting as integer gap of 0.038215965 less than 0 or 0.01%`

Same thing with the absolute tolerance:

```
using AmplNLWriter
solver = CouenneNLSolver()
open("couenne.opt", "w") do f
    write(f, "allowable_gap 5")
end
include(joinpath(Pkg.dir("AmplNLWriter"), "examples", "jump_pruning.jl"))
```

which shows something like `Exiting as integer gap of 3.8642216 less than 5 or 0%`

Hopefully that should pick it up!

**Comment by madeleineudell** [comment]
That works! I suppose Couenne just doesn't know how to take advantage of an increased in the allowed gap for my problem.

**Comment by JackDunnNZ** [comment]
Okay great! Miles might have more of an idea of how to get it working on your problem, I've never used it in any real capacity

**Comment by mlubin** [comment]
No idea here. @emreyamangil and I once spent a day or so digging around Bonmin's source code to try and find its termination criteria without any success. I haven't looked at couenne but I'm guessing it might not be any easier.
