### ISSUE TITLE
Using SCIP fron AmplNLWriter

### ISSUE THREAD

**Issue by madeleineudell** [JuliaOpt/AmplNLWriter.jl#26]
It looks like the invocation of SCIP from AmplNLWriter is different than what my installed version of SCIP expects. I get the error:
```
invalid parameter </Users/madeleine/.julia/v0.4/AmplNLWriter/.solverdata/model.nl>
invalid parameter <-AMPL>

syntax: /Applications/scipoptsuite-3.2.0/scip-3.2.0/bin/scip [-l <logfile>] [-q] [-s <settings>] [-f <problem>] [-b <batchfile>] [-c "command"]
  -l <logfile>  : copy output into log file
  -q            : suppress screen messages
  -s <settings> : load parameter settings (.set) file
  -f <problem>  : load and solve problem file
  -b <batchfile>: load and execute dialog command batch file (can be used multiple times)
  -c "command"  : execute single line of dialog commands (can be used multiple times)
```
The command that seems to be being called inside AmplNLWriter is 
```scip /Users/madeleine/.julia/v0.4/AmplNLWriter/.solverdata/model.nl -AMPL```
Being unfamiliar with SCIP in its non-Julian incarnations, I'm not sure what the right syntax for calling it with an AMPL file is, or whether I need to compile a different version of it...? I've compiled it according to the instructions [here](https://github.com/ryanjoneil/SCIP.jl).

**Comment by JackDunnNZ** [comment]
We have been meaning to document this properly (JuliaOpt/JuMP.jl#588), but you need to follow the instructions [here](http://zverovich.net/2012/08/07/using-scip-with-ampl.html) to compile it with ASL support for the .nl interface (and the -AMPL flag) to work. Let me know if that doesn't work

**Comment by madeleineudell** [comment]
Yes, that works! 

SCIP seems to run forever on my problem without knowing how to specify an abstol, but that's another (solver options) question...

**Comment by JackDunnNZ** [comment]
Great! I haven't tried it out, but `scipampl` seems to want a settings file as well to set options (sigh):

```
> scipampl
SCIP version 3.2.0 [precision: 8 byte] [memory: block] [mode: optimized] [LP solver: SoPlex 2.2.0] [GitHash: fb0007a]
Copyright (c) 2002-2015 Konrad-Zuse-Zentrum fuer Informationstechnik Berlin (ZIB)

Usage: scipampl <nl-file> { [-AMPL] | [<settings-file>] | -i }

       -i starts the SCIP shell after reading settings and .nl file, instead of starting the SCIP solve
```

The valid options seem to be listed here: http://plato.asu.edu/milp/scip.set

**Comment by madeleineudell** [comment]
Cool. How can I modify the call AmplNLWriter makes to tell scipampl where
the options file is?

On Thu, Dec 17, 2015 at 7:48 PM, Jack Dunn <notifications@github.com> wrote:

> Great! I haven't tried it out, but scipampl seems to want a settings file
> as well to set options (sigh):
>
> > scipampl
> SCIP version 3.2.0 [precision: 8 byte] [memory: block] [mode: optimized] [LP solver: SoPlex 2.2.0] [GitHash: fb0007a]
> Copyright (c) 2002-2015 Konrad-Zuse-Zentrum fuer Informationstechnik Berlin (ZIB)
>
> Usage: scipampl <nl-file> { [-AMPL] | [<settings-file>] | -i }
>
>        -i starts the SCIP shell after reading settings and .nl file, instead of starting the SCIP solve
>
> The valid options seem to be listed here:
> http://plato.asu.edu/milp/scip.set
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/AmplNLWriter.jl/issues/26#issuecomment-165662673>
> .
>



-- 
Madeleine Udell
Postdoctoral Fellow at the Center for the Mathematics of Information
California Institute of Technology
*https://courses2.cit.cornell.edu/mru8
<https://courses2.cit.cornell.edu/mru8>*
(415) 729-4115

**Comment by JackDunnNZ** [comment]
Currently we presume that the options after `-AMPL` are of the form `key=value` which isn't going to work with SCIP. 

The start of the call is always going to look like `solverbinary file.nl -AMPL` and then have extra options depending on the situation.

Maybe we could switch from a Dict of key/value options to an array of strings, which would allow people to specify options that don't come out as `key=value` as well? I'm not really sure, what do you (and also @mlubin) think?

**Comment by mlubin** [comment]
An array of strings seems fine to me

**Comment by madeleineudell** [comment]
That works! (That is, I checked out the options branch.) Thanks so much for all your help!

**Comment by JackDunnNZ** [comment]
Great! I've merged the options branch now
