### ISSUE TITLE
Assertion error: numcons == m.ncon

### ISSUE THREAD

**Issue by madeleineudell** [JuliaOpt/AmplNLWriter.jl#27]
Something seems to have broken now (after trying to use the SCIP solver, but without having made any changes in the AmplNLWriter repo compared to master), and I'm not sure what to look for in debugging it. With a simple example that used to work (pasted below), I now get the following error:
```
~/.julia/v0.4/SigmoidalProgramming (a6a8a5f ✘)✭ ᐅ julia examples/simple.jl
ERROR: LoadError: AssertionError: num_cons == m.ncon
 in read_sol at /Users/madeleine/.julia/v0.4/AmplNLWriter/src/AmplNLWriter.jl:574
 in read_results at /Users/madeleine/.julia/v0.4/AmplNLWriter/src/AmplNLWriter.jl:484
 in optimize! at /Users/madeleine/.julia/v0.4/AmplNLWriter/src/AmplNLWriter.jl:353
 in optimize! at /Users/madeleine/.julia/v0.4/AmplNLWriter/src/AmplNLWriter.jl:663
 in solvenlp at /Users/madeleine/.julia/v0.4/JuMP/src/nlp.jl:547
 in solve at /Users/madeleine/.julia/v0.4/JuMP/src/solvers.jl:135
 in include at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in process_options at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/madeleine/.julia/v0.4/SigmoidalProgramming/examples/simple.jl, in expression starting on line 14
```
and here's `examples/simple.jl`:
```
using JuMP, AmplNLWriter, MathProgBase

srand(4)
nvar = 10

solver=AmplNLSolver("couenne")
m = Model(solver=solver)
@defVar(m, -10 <= x[i=1:nvar] <= 10)
@setNLObjective(m, Min, sum{1/(1+exp(-x[i])), i=1:nvar})
@addConstraint(m, sum{x[i], i=1:nvar} <= .4*nvar)
@assert(solve(m) == :Optimal)
```

**Comment by JackDunnNZ** [comment]
Is it reproducible on your end (or with other solvers)? It seems to work fine for me, but it sounds like the `.sol` file is malformed. Can you find the relevant `.nl` and `.sol` files from the `AmplNLWriter/.solverdata` folder and link them here?

**Comment by madeleineudell** [comment]
Yes, it's reproducible, but the problem only seems to be happening with
Couenne. (I have SCIP working fine now.) The .solverdata is [here](
https://gist.github.com/madeleineudell/abccfff6b560312c564e). (I think the
`model.sol` must correspond to a different run...? It's not updated when I
run `simple.jl`.)

On Thu, Dec 17, 2015 at 7:16 PM, Jack Dunn <notifications@github.com> wrote:

> Is it reproducible on your end (or with other solvers)? It seems to work
> fine for me, but it sounds like the .sol file is malformed. Can you find
> the relevant .nl and .sol files from the AmplNLWriter/.solverdata folder
> and link them here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/AmplNLWriter.jl/issues/27#issuecomment-165657709>
> .
>



-- 
Madeleine Udell
Postdoctoral Fellow at the Center for the Mathematics of Information
California Institute of Technology
*https://courses2.cit.cornell.edu/mru8
<https://courses2.cit.cornell.edu/mru8>*
(415) 729-4115

**Comment by JackDunnNZ** [comment]
Could you try with the `random-name` branch (#23)? I just realized that it hasn't been merged yet, but it should catch any errors relating to stale files

**Comment by madeleineudell** [comment]
Seems like that branch doesn't work with the MathProgBase restructuring;
I'll have to do a merge...

On Thu, Dec 17, 2015 at 7:40 PM, Jack Dunn <notifications@github.com> wrote:

> Could you try with the random-name branch (#23
> <https://github.com/JuliaOpt/AmplNLWriter.jl/pull/23>)? I just realized
> that it hasn't been merged yet, but it should catch any errors relating to
> stale files
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/AmplNLWriter.jl/issues/27#issuecomment-165661533>
> .
>



-- 
Madeleine Udell
Postdoctoral Fellow at the Center for the Mathematics of Information
California Institute of Technology
*https://courses2.cit.cornell.edu/mru8
<https://courses2.cit.cornell.edu/mru8>*
(415) 729-4115

**Comment by JackDunnNZ** [comment]
Whoops, I'll rebase it now, sorry!

**Comment by madeleineudell** [comment]
even worse:
```
ERROR: LoadError: SystemError: opening file /Users/madeleine/.julia/v0.4/AmplNLWriter/.solverdata/tmpkCcVa2.sol: No such file or directory
 in open at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in open at iostream.jl:102
 in read_sol at /Users/madeleine/.julia/v0.4/AmplNLWriter/src/AmplNLWriter.jl:569
 in read_results at /Users/madeleine/.julia/v0.4/AmplNLWriter/src/AmplNLWriter.jl:514
 in optimize! at /Users/madeleine/.julia/v0.4/AmplNLWriter/src/AmplNLWriter.jl:376
 in optimize! at /Users/madeleine/.julia/v0.4/AmplNLWriter/src/AmplNLWriter.jl:695
 in solvenlp at /Users/madeleine/.julia/v0.4/JuMP/src/nlp.jl:547
 in solve at /Users/madeleine/.julia/v0.4/JuMP/src/solvers.jl:135
 in include at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in process_options at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/madeleine/.julia/v0.4/SigmoidalProgramming/examples/simple.jl, in expression starting on line 11
```

**Comment by JackDunnNZ** [comment]
So I think something is preventing it from writing the .sol file with the name it expects, perhaps it's being overridden by a parameter. Does it happen if you delete the `couenne.opt` file (or try disabling some of the parameters)?

**Comment by madeleineudell** [comment]
I've moved the options file and am calling the solver with no options, but
still see the same problem.

On Thu, Dec 17, 2015 at 9:02 PM, Jack Dunn <notifications@github.com> wrote:

> So I think something is preventing it from writing the .sol file with the
> name it expects, perhaps it's being overridden by a parameter. Does it
> happen if you delete the couenne.opt file (or try disabling some of the
> parameters)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/AmplNLWriter.jl/issues/27#issuecomment-165673989>
> .
>



-- 
Madeleine Udell
Postdoctoral Fellow at the Center for the Mathematics of Information
California Institute of Technology
*https://courses2.cit.cornell.edu/mru8
<https://courses2.cit.cornell.edu/mru8>*
(415) 729-4115

**Comment by JackDunnNZ** [comment]
What if you try with `CouenneNLSolver()` instead of `AmplNLSolver("couenne")` to make sure we are using the same couenne from CoinOptServices.jl (mine is v0.5.6). And does the example work with other solvers?

I guess the next step after that is to try running the solver command-line directly on the .nl file and see if/why it isn't making a .sol file, or what files it is generating.

**Comment by madeleineudell** [comment]
With `CouenneNLSolver()` it works again! No errors.

I still don't seem to be able to set the absolute tolerance, either from the options file or from the list of keyword arguments, despite trying all three of "bonmin.allowable_gap", "allowable_gap", and "allowable_fraction_gap". I do get the reassuring warning that Couenne has read in the options file and refuses to allow the options to be overridden by the keyword arguments.
