### ISSUE TITLE
How to write a .nl file

### ISSUE THREAD

**Issue by samiit** [JuliaOpt/AmplNLWriter.jl#40]
Sorry for asking a naive question.

I've been looking for a function that can write a model down in .nl file that I can test with different solvers (e.g., on NEOS).

How shall I write the model into a .nl file? E.g., in the example code [here](https://github.com/JuliaOpt/AmplNLWriter.jl/blob/master/examples/jump_minlp.jl).

Regards,

Sam

**Comment by JackDunnNZ** [comment]
No problem at all, it's not obvious or documented. You can do that using the `setdebug` function to keep the .nl file around after the solve, and the `filename` option in the solver to specify a useful name for the .nl file:

```julia
using JuMP, AmplNLWriter

AmplNLWriter.setdebug(true)
m = Model(solver=BonminNLSolver(filename="mymodel"))

x_U = [2,2,1]
@variable(m, x_U[i] >= x[i=1:3] >= 0)
@variable(m, y[4:6], Bin)

@NLobjective(m, Min, 10 + 10*x[1] - 7*x[3] + 5*y[4] + 6*y[5] + 8*y[6] - 18*log(x[2]+1) - 19.2*log(x[1]-x[2]+1))
@NLconstraint(m, 0.8*log(x[2] + 1) + 0.96*log(x[1] - x[2] + 1) - 0.8*x[3] >= 0)
@NLconstraint(m, log(x[2] + 1) + 1.2*log(x[1] - x[2] + 1) - x[3] - 2*y[6] >= -2)
@NLconstraint(m, x[2] - x[1] <= 0)
@NLconstraint(m, x[2] - 2*y[4] <= 0)
@NLconstraint(m, x[1] - x[2] - 2*y[5] <= 0)
@NLconstraint(m, y[4] + 2*y[5]*0.5 <= 1)

solve(m)
```

The .nl file will be here: `~/.julia/v0.4/AmplNLWriter/.solverdata/mymodel.nl`

**Comment by samiit** [comment]
Thanks Jack. And what if I want to create one for another solver, say Gurobi or CBC?

**Comment by samiit** [comment]
Hi Jack,
The .nl file when uploaded to the NEOS solver throws error regarding the first line already. (I know about [NEOS.jl](https://github.com/odow/NEOS.jl), but I have other [issues](https://github.com/odow/NEOS.jl/issues/5) about that!)

Can you check the validity of the .nl file generated by the above code example?

Sam

**Comment by JackDunnNZ** [comment]
Hi Sam,

I can't see where to submit a .nl file on the NEOS site, can you point me to the right place?

For other solvers, you can use the same .nl files, they are solver-independent. Although it is more complicated to run CBC or Gurobi with an .nl file since they don't support them out of the box. If you want more info on this let me know.

**Comment by samiit** [comment]
Hi Jack,

It was due to my lack of understanding of the AMPL file format. I guess what they expect on the NEOS site is not the .nl file format but instead the .mod file format for AMPL. I would be glad to get some more info if you have.

Thanks.

**Comment by JackDunnNZ** [comment]
Oh, yes that's right about .mod vs .nl, sorry for the confusion

For CBC, you need a version of the solver that is compiled with ASL support. The [downloads on the AMPL site](http://ampl.com/products/solvers/open-source/) have this, or you can compile it yourself manually if you'd prefer. Then you have to use a different command line syntax to run on the .nl file, the only reference for that I have is slide 19 [here](http://dimacs.rutgers.edu/Workshops/COIN/slides/forest2.pdf)

For Gurobi, you have to download and set up the `gurobi_ampl` binary in addition to the normal Gurobi solver, which handles reading the .nl files and passing the problem to the standard solver. Gurobi's guide on installation/use of this binary is [here](http://www.gurobi.com/documentation/6.5/ampl-gurobi/index.html)
