### ISSUE TITLE
slow writing nl with a big linear part

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/AmplNLWriter.jl#46]
https://gist.github.com/mlubin/2ad311fbe2378367c08ff2fd9067b9ac
Download and run ``bunzip2`` on ``dump.jld.bz2``. Also needs the master branch of ConicNonlinearBridge. I've left the code running for a number of minutes and it seems to hang on writing the NL file. If I use Ipopt through the native interface with JuMP's AD, it gets up and running in a few seconds and solves in a minute.

**Comment by JackDunnNZ** [comment]
#48 fixes this, the linear writer was needless looping over all variables rather than just the ones present in the constraint

**Comment by mlubin** [comment]
@JackDunnNZ, that'll do it, thanks!
