### ISSUE TITLE
Nonlinear objective evaluation after solve is very slow

### ISSUE THREAD

**Issue by JackDunnNZ** [JuliaOpt/AmplNLWriter.jl#51]
I have the following simple regularized logistic regression problem:

```julia
function logistic_regression(X::Matrix{Float64}, y::Vector{Int}, λ::Float64)
  n, p = size(X)

  # Convert y to (-1, +1)
  Y = y * 2 - 3

  m = Model(solver=IpoptNLSolver())

  @variables m begin
    β[1:p]
    β0
    z[1:p] >= 0
  end
  @NLexpression(m, fx[i=1:n], sum{X[i, j] * β[j], j= 1:p} + β0)

  @constraints m begin
    pos_abs[i = 1:p], z[i] >=  β[i]
    neg_abs[i = 1:p], z[i] >= -β[i]
  end

  @NLobjective(m, Max, -sum{log(1 + exp(-Y[i] * fx[i])), i = 1:n} -
                          n * λ * sum{z[j], j=1:p})

  @time status = solve(m)

  getvalue(β), getvalue(β0)
end
```

X is a 23000x128 matrix. Ipopt finishes in about 10 seconds, but then evaluating the objective value takes around 80s at [this step](https://github.com/JuliaOpt/AmplNLWriter.jl/blob/master/src/AmplNLWriter.jl#L584), in particular the `substitute_vars!` call is the slow one, which traverses the expression tree and replaces variable nodes with their numeric solutions.

@mlubin Do you have any ideas about how we could make this step faster?

Interestingly, solving the same problem via Ipopt.jl takes 250 seconds (all in function evaluations), so there's about a 25x difference in just the raw solve time, ignoring this objective value time.

**Comment by mlubin** [comment]
``eval`` doesn't scale linearly with the input. I can only really recommend making your own expression interpreter.

**Comment by JackDunnNZ** [comment]
Is there any way we can hand off the current solution to the JuMP NLPEvaluator to get the function value once or something like that?

**Comment by mlubin** [comment]
You could construct a new JuMP model and load in the expression using the raw input format (http://www.juliaopt.org/JuMP.jl/0.14/nlp.html#raw-expression-input).

**Comment by mlubin** [comment]
Wait, you already have a JuMP NLPEvaluator, just call it?

**Comment by JackDunnNZ** [comment]
Like this right? https://github.com/JuliaOpt/Ipopt.jl/blob/master/src/IpoptSolverInterface.jl#L53

**Comment by mlubin** [comment]
Yes

**Comment by JackDunnNZ** [comment]
Thanks, I'll have a look at it later
