### ISSUE TITLE
Overwrite temporary files

### ISSUE THREAD

**Issue by jcheyns** [JuliaOpt/AmplNLWriter.jl#60]
I am running a series of optimization models consecutively. The loop fails 'sometimes' due to the fact that the temporary .nl files do not seem to be able to overwrite each other.
I guess the culprit is at line 375  in AmplNLWriter.jl :

    # Rename file to have .nl extension (this is required by solvers)
    mv(file_basepath, m.probfile)

this should use the option remove_destination=true

**Comment by jcheyns** [comment]
#62

**Comment by odow** [comment]
Resolved by https://github.com/JuliaOpt/AmplNLWriter.jl/pull/63
