### ISSUE TITLE
Julia v0.6 Support?

### ISSUE THREAD

**Issue by ccoffrin** [JuliaOpt/AmplNLWriter.jl#65]
Is this currently working in Julia v0.6?  I notice that v0.6 is not in CI.  I am currently getting this message,

```
ERROR: LoadError: MethodError: no method matching setsolver(::JuMP.Model, ::AmplNLWriter.AmplNLSolver)
The applicable method may be too new: running in world age 21832, while current world is 21843.
```
@jac0320, @kaarthiksundar do you two have similar issues?

**Comment by mlubin** [comment]
This package's conditional dependency on Ipopt and CoinOptServices could cause issues like this.

**Comment by ccoffrin** [comment]
In theory would it possible to make this package more independent and robust?  NL is a very convenient way to access a wide range of established solvers.

**Comment by odow** [comment]
> make this package more independent and robust

I'm planning on tidying this up over the next few weeks. ref #66

**Comment by ccoffrin** [comment]
Great!  Happy to help in what limited capacity I can.  If you add "help wanted" issues here I can try to do some of them.

**Comment by ccoffrin** [comment]
Just an FYI.  After v0.4.0 was tagged I still had this issue.  The problem was something along these lines,
```
using AmplNLWriter

include("some file") # this file imported JuMP and defined a model "m"

solver = AmplNLSolver("some_solver")
setsolver(m, solver) # this method call failed
```
The root of issue seems to be how Julia deals with package imports combined with include.  The fix was to explicitly add JuMP to the master script like so,
```
using JuMP
using AmplNLWriter

include("some file")

solver = AmplNLSolver("bonmin", optoins)
setsolver(m, solver) # this method call works
```
