### ISSUE TITLE
Bonmin: Cannot open .nl file

### ISSUE THREAD

**Issue by walkingzen** [JuliaOpt/AmplNLWriter.jl#78]
I was trying to solve a Non linear integer optimization problem as given below: But getting an error saying cannot open .nl file. I did not understood why does it happening. 

Max 4.085381103967961e-6 * (0.02789 * (1.0 - 0.3 ^ zj[1]) * (*)(0.3 ^ zj[1]) + 0.011173 * (1.0 - 0.3 ^ zj[3]) * (0.3 ^ zj[1] * 0.3 ^ zj[3]) + 0.00097 * (1.0 - 0.3 ^ zj[2]) * (0.3 ^ zj[1] * 0.3^ zj[3] * 0.3 ^ zj[2])) + 1.08158767640779e-5 * (0.081077 * (1.0 - 0.3 ^ zj[1]) * (*)(0.3 ^ zj[1]) + 0.003674 * (1.0 - 0.3 ^ zj[3]) * (0.3 ^ zj[1] * 0.3 ^ zj[3]) + 0.002916 * (1.0 - 0.3 ^ zj[2]) * (0.3 ^ zj[1] * 0.3 ^ zj[3] * 0.3 ^ zj[2])) + 1.714709723075756e-5 * (0.041535 * (1.0 - 0.3 ^ zj[1]) * (*)(0.3 ^ zj[1]) + 0.004603 * (1.0 - 0.3 ^ zj[2]) * (0.3 ^ zj[1] * 0.3 ^ zj[2]) + 0.002542 * (1.0 - 0.3 ^ zj[3]) * (0.3 ^ zj[1] * 0.3 ^ zj[2] * 0.3 ^ zj[3])) + 6.390409502891686e-6 * (0.015394 * (1.0 - 0.3 ^ zj[1]) * (*)(0.3 ^ zj[1]) + 0.004482 * (1.0 - 0.3 ^ zj[3]) * (0.3 ^ zj[1] * 0.3 ^ zj[3]) + 0.001687 * (1.0 - 0.3 ^ zj[2]) * (0.3 ^ zj[1] * 0.3 ^ zj[3] * 0.3 ^ zj[2])) + 3.2934853036645695e-5 * (0.213073 * (1.0 - 0.3 ^ zj[1]) * (*)(0.3 ^ zj[1]) + 0.008925 * (1.0 - 0.3 ^ zj[2]) * (0.3 ^ zj[1] * 0.3 ^ zj[2]) + 0.00121 * (1.0 - 0.3 ^ zj[3]) * (0.3 ^ zj[1] * 0.3 ^ zj[2] * 0.3 ^ zj[3])) + 1.3446277661500508e-6 * (0.458692 * (1.0 - 0.3 ^ zj[1]) * (*)(0.3 ^ zj[1]) + 0.026056 * (1.0 - 0.3 ^ zj[2]) * (0.3 ^ zj[1] * 0.3 ^ zj[2]) + 0.000423 * (1.0 - 0.3 ^ zj[3]) * (0.3 ^ zj[1] * 0.3 ^ zj[2] * 0.3 ^ zj[3]))
Subject to
 zj[1] ≤ 1
 zj[2] ≤ 1
 zj[3] ≤ 1
 zj[1] + zj[2] + zj[3] ≤ 3
 zj[i] ≥ 0, integer, ∀ i ∈ {1,2,3}
Bonmin 1.8.6 using Cbc 2.9.9 and Ipopt 3.12.8
bonmin:
Cannot open .nl file

The code I used is 

        mexclp_pr_ssbp = Model(solver=AmplNLSolver(
                                    "/path/to/bonmin/bonmin"))

        @variable(mexclp_pr_ssbp, zj[1:n] >=0 , Int)

        for j in 1:n
            @constraint(mexclp_pr_ssbp, zj[j] <= cj[j] )
        end
        @constraint(mexclp_pr_ssbp, sum(zj) <= q )

        @NLobjective(mexclp_pr_ssbp, Max,
                    sum(di[i] *
                    sum(P[i,ij[i,j]] *
                    (1 - p[ij[i,j]]^zj[ij[i,j]]) * prod(p[ij[i,j]] ^ zj[ij[i,u]] for u in 1:(j)) for j in 1:n )
                    for i in 1:m))

        print(mexclp_pr_ssbp)

        # setvalue(zj, cj)
        solve(mexclp_pr_ssbp)

It is working if I used sum instead of prod in the code. Any help would be appreciated.

**Comment by muriloasouza** [comment]
I'm having a similar issue, this is my code:

```
using JuMP, AmplNLWriter

## Solve test problem with non-linear binary variables
 #
 #  min   100 * (x2 - (0.5 + x1) ^ 2) ^ 2 + (1 - x1) ^ 2
 #  s.t.  x1, x2 binary
 #
 #  The solution is (0, 0).
 ##
 m = Model(solver = AmplNLSolver("bonmin"))
 
 @variable(m, x[1:2], Bin)
 
 @NLobjective(m, Min, 100*(x[2] - (0.5 + x[1])^2)^2 + (1 - x[1])^2)
 

 print(m)
 
 status = solve(m)
 
 println("Objective value: ", getobjectivevalue(m))
 println("x = ", getvalue(x))
```
And i get the following error:

> could not spawn `bonmin 'C:\Users\LDSP-vPro-2\AppData\Local\JuliaPro\pkgs-0.6.2.2\v0.6\AmplNLWriter\.solverdata\jl_6B58.tmp.nl' -AMPL`: no such file or directory (ENOENT) 

I'm really new to Julia, so i have no idea what i'm doing wrong here. Any help will be trully appreciated!
