### ISSUE TITLE
tests fail on 1.2 (dependency issue?)

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaOpt/AmplNLWriter.jl#86]
It looks like this package brings in an older version of JuMP during testing, which fails to load on 1.2 due to the invalid `:import` expression thing that was fixed a while ago in JuMP. Can the test dependencies just be updated or is there a deeper problem?

**Comment by odow** [comment]
Probably things just need to be updated. I'll have a look later today. There aren't any deeper problems.

**Comment by mlubin** [comment]
We already have a fix for the 0.18 branch of JuMP for Julia 1.2 that's not tagged yet, so nothing immediately surprising here. From your side it's probably safe to ignore this failure.

**Comment by JeffBezanson** [comment]
Great, thanks!
