### ISSUE TITLE
Syntax for Knitro with outlev

### ISSUE THREAD

**Issue by felipeb95** [JuliaOpt/AmplNLWriter.jl#89]
Hi, I'm currently using Knitro solver in AmplNLWriter and I want to set the outlev for Knitro. Actually I have only `m = Model(with_optimizer(AmplNLWriter.Optimizer, "knitro"))` and I want to add the outlev.

**Comment by odow** [comment]
Hi @felipeb95,

There is some documentation in the README about how to pass options:
https://github.com/JuliaOpt/AmplNLWriter.jl#usage

I don't have Knitro, so I can't test, but you can try
```Julia
model = Model(with_optimizer(AmplNLWriter.Optimizer, "knitro", ["outlev=3"]))
```

Note that if you have KNITRO v11 or greater, you can use https://github.com/JuliaOpt/KNITRO.jl.

(@frapac: FYI.)

**Comment by odow** [comment]
Closing as stale. This doesn't appear to be an issue with AmplNLWriter.jl. Please re-open if that isn't the case.
