### ISSUE TITLE
Couenne gives error for output

### ISSUE THREAD

**Issue by dmit4git** [JuliaOpt/AmplNLWriter.jl#92]
Hi there!
I’m trying to use [Couenne](https://projects.coin-or.org/Couenne) optimizer with AmplNLWriter, but can’t make it work.
Here’s my hello-world level model:
```julia
using JuMP, AmplNLWriter
model = Model(with_optimizer(AmplNLWriter.Optimizer, "/usr/local/bin/couenne"))
@variable(model, 0 <= x <= 2 )
@variable(model, 0 <= y <= 30 )
@objective(model, Max, 5x + 3*y )
@constraint(model, 1x + 5y <= 3.0 )
optimize!(model)
```
Couenne produces error for result, when I try to printout results of the optimization with
```julia
println(JuMP.termination_status(model))
println("Objective value: ", JuMP.objective_value(model))
println("x = ", JuMP.value(x))
println("y = ", JuMP.value(y))
```
I get
```
OTHER_ERROR
Objective value: NaN
x = NaN
y = NaN
```
[Juniper](https://github.com/lanl-ansi/Juniper.jl) gives expected (no-error) result solving this problem and Couenne does too if I run it with [AMPL](https://ampl.com/) or as a standalone solver.

**Comment by odow** [comment]
I cannot reproduce this. I get the optimal solution on current master.

**Comment by dmit4git** [comment]
Tried to reproduce it with current versions of packages (JuMP v0.21.1, AmplNLWriter v0.5.0) and got an error on attempt to build JuMP model:
```Julia
model = Model(with_optimizer(AmplNLWriter.Optimizer, "/usr/local/bin/couenne"))
```
```
LoadError: The provided `optimizer_constructor` returned an object of type MathOptInterface.Utilities.Univer
salFallback{AmplNLWriter.InnerModel{Float64}}. Expected a MathOptInterface.AbstractOptimizer.
```

**Comment by odow** [comment]
Should be fixed on `master`. Needs a new tag.
